---
# tasks file for /vagrant/playing/netdata
- name: install netdata dependencies
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - zlib1g-dev
    - gcc
    - make
    - git
    - autoconf
    - autogen
    - automake
    - pkg-config

- name: clone the netdata repository
  git: repo=https://github.com/firehol/netdata.git dest=/root/netdata depth=1

- name: run the netdata install script
  command: ./netdata-installer.sh --dont-wait chdir=/root/netdata/
