---
- name: apply common configuration to all the servers
  hosts: all
  remote_user: ubuntu
  sudo: yes
  roles:
  - common

- name: setup elasticsearch server
  hosts: elasticsearch-node
  remote_user: ubuntu
  sudo: yes
  roles:
  - orajava
  - elasticsearch

- name: setup logstash server
  hosts: logstash-node
  remote_user: ubuntu
  sudo: yes
  roles:
  - orajava
  - logstash


- name: setup kibana ui
  hosts: kibana-node
  remote_user: ubuntu
  sudo: yes
  roles:
  - apache2
  - kibana
