---
- name: apply common configuration to all the servers
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
  - common

- name: setup elasticsearch server
  hosts: elasticsearch-node
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
  - orajava
  - elasticsearch

- name: setup logstash server
  hosts: logstash-node
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
  - orajava
  - logstash


- name: setup kibana ui
  hosts: kibana-node
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
  - kibana
  - nginx
