---
- name: apply common configuration to all the servers
  hosts: all
  remote_user: root
  roles:
  - common

- name: setup redis master
  hosts: redis-master
  remote-user: root
  roles:
  - base-redis
  - rmaster

- name: setup redis slave(s)
  hosts: redis-slaves
  remote_user:
  - base-redis
  - rslaves
